- name: "Installing haproxy"
  apt:
    update_cache: "yes"
    name:
      - haproxy
    state: latest
- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy
- name: Enable haproxy service
  become: true
  ansible.builtin.service:
    name: haproxy
    enabled: true
    state: restarted