---
# tasks file for debian-prep
- name: Updating OS
  apt:
    force_apt_get: true
    update_cache: true
    state: latest
    name: "*"

- name: Installing additional packages
  apt:
    name:
      - bash-completion
      - curl
      - wget
      - git
      - net-tools
      - unzip
      - ca-certificates
      - jq
      - gnupg
      - software-properties-common
      - apt-transport-https
      - unattended-upgrades
    state: latest
    update_cache: true

- name: Clean up dependencies
  become: true
  apt:
    autoremove: yes
    autoclean: yes

- name: Remove default user
  ansible.builtin.user:
    name: ubuntu
    state: "absent"
    remove: true

- name: Configuring auto update service
  become: true
  shell: |
    cat << "EOF" | sudo tee /etc/apt/apt.conf.d/50unattended-upgrades
    Unattended-Upgrade::Allowed-Origins {
            "${distro_id}:${distro_codename}";
            "${distro_id}:${distro_codename}-security";
            "${distro_id}ESMApps:${distro_codename}-apps-security";
            "${distro_id}ESM:${distro_codename}-infra-security";
    };
    Unattended-Upgrade::Package-Blacklist {
    };
    Unattended-Upgrade::DevRelease "auto";
    EOF
    cat << EOF | sudo tee /etc/apt/apt.conf.d/20auto-upgrades
    APT::Periodic::Update-Package-Lists "1";
    APT::Periodic::Unattended-Upgrade "1";
    APT::Periodic::AutocleanInterval “7”;
    EOF

- sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes
  loop:
    - net.ipv6.conf.lo.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6 
    - net.ipv6.conf.all.disable_ipv6

- sysctl:
    name: "{{ item }}" 
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
  loop: 
    - net.ipv4.conf.all.accept_redirects

- name: Configuring static IP
  become: true
  shell: |
    rm /etc/netplan/*;
    GATEWAY_IP=$(ip route | grep "default" | awk '{print $3}');
    cat <<EOF | tee /etc/netplan/netconf.yaml
    network:
      version: 2
      renderer: networkd
      ethernets:
        {{ ansible_default_ipv4.interface }}:
          dhcp4: no
          dhcp6: no
          addresses:
            - {{ ansible_default_ipv4.address }}/24
          routes:
          - to: default
            via: $GATEWAY_IP
          nameservers: 
            addresses: [1.1.1.1, 1.0.0.1]
    EOF

- name: Apply netplan
  become: true
  command: netplan apply
  async: 45
  poll: 0

- name: "Check install docker: {{ lookup('env', 'INSTALL_DOCKER') }}"
  include_tasks: "docker.yml"
  when: "lookup('env', 'INSTALL_DOCKER') == '1'"